config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'persons#index'
  resources :persons
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def index
    @person = Person.all
  end
  
  def new
    @person = Person.new
  end
  
  def create
    Person.create(person_params)
    redirect_to root_path
  end
  
  private
  
  def person_params
    params.require(:person).permit(:about, :resident)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/persons/index.html.erb
<h1 class="pink">Welcome Nomads!</h1>

<br/>
<h2 class="pink"><%= link_to 'Click Here Tell Us About Youself', new_person_path %></h2>
<br/>

app/views/persons/new.html.erb
<h1 class="pink">Tell Us About You</h1>
<br/>
<br/>
<%= simple_form_for @person, url: persons_path do |f| %>
  <%= f.input :about %>
  <br/>
  <%= f.input :resident %>
  <br/>
  <%= f.submit 'Share!' %>
  
<% end %>